### ISSUE TITLE
Hospitality module not working with version 14

### ISSUE THREAD

**Issue by chandrubiradar** [frappe/hospitality#8]
I have installed it on my site.
Which has ERPNEXT and Frappe has version 14.

I don't see this application is working.
I even checked all the doctypes under Hotel and Restaurant modules. I see page not found error for all the doctypes.

Please suggest any alternatives to make HOSPITALITY module working with version 14.

**Comment by pwhilgert** [comment]
I was able to load hospitality app in version 14. 

Try this...go to the magic bar and go to doctype list. Select Hotel Settings doctype and click on button to create Hotel Settings. Once you create some settings you should see all the other Hotel doc types display in the magic bar.

**Comment by chandrubiradar** [comment]
@pwhilgert  Let me try this
Thanks for your responce
